version: '3.7'
name: 'streaming'
services:
  rtmp:
    build: ./rtmp
    ports:
      - 1935:1935
      - 3000:3000
    volumes:
      - ./data:/tmp/hls
    restart: always
  auth-server:
    build: ./auth
    volumes:
      - ./auth:/app
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  haproxy:
    image: haproxy:latest
    ports:
      - 5000:5000
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    container_name: haproxy
    restart: always